[project]
name = "ai-demo"
version = "0.1.0"
description = "Nick Earl Portfolio AI Demo"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "dash[compress]>=3.2.0",
    "dash-ag-grid>=31.2.0",
    "dash-bootstrap-components>=2.0.4",
    "flask>=3.1.2",
    "google-genai",
    "google-cloud-secret-manager>=2.24.0",
    "gunicorn>=23.0.0",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "plotly>=6.3.0",
    "python-dotenv>=1.1.1",
]
